# Generated by Django 5.1.4 on 2026-02-22 01:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='currency',
            field=models.CharField(choices=[('QAR', 'QAR - Qatari Riyal'), ('USD', 'USD - US Dollar'), ('GBP', 'GBP - British Pound'), ('JOD', 'JOD - Jordanian Dinar'), ('EGP', 'EGP - Egyptian Pound')], default='QAR', max_length=3),
        ),
        migrations.AddField(
            model_name='project',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, help_text='Exchange rate used: 1 original currency = X QAR', max_digits=10),
        ),
        migrations.AddField(
            model_name='project',
            name='fee_in_original',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fee in original currency (before conversion to QAR)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_fee',
            field=models.DecimalField(decimal_places=2, help_text='Total fee in QAR', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
