# Generated by Django 5.1.4 on 2026-02-22 01:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_currency_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duration', models.DecimalField(decimal_places=1, help_text='Duration in hours (e.g. 1.0, 1.5, 2.0)', max_digits=3, validators=[django.core.validators.MinValueValidator(0.5)])),
                ('student_hourly_rate', models.DecimalField(decimal_places=2, help_text='Rate charged to student per hour (QAR)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('teacher_hourly_rate', models.DecimalField(decimal_places=2, help_text='Rate paid to teacher per hour (QAR)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('student_payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('student_paid_date', models.DateField(blank=True, null=True)),
                ('teacher_payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('teacher_paid_date', models.DateField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='private_classes', to='core.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='private_classes', to='core.teacher')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
