# Generated by Django 5.1.4 on 2026-02-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_populate_default_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateclass',
            name='teacher_currency',
            field=models.CharField(choices=[('QAR', 'QAR - Qatari Riyal'), ('USD', 'USD - US Dollar'), ('GBP', 'GBP - British Pound'), ('JOD', 'JOD - Jordanian Dinar'), ('EGP', 'EGP - Egyptian Pound')], default='QAR', max_length=3),
        ),
        migrations.AddField(
            model_name='privateclass',
            name='teacher_exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, help_text='Exchange rate used: 1 teacher currency = X QAR', max_digits=10),
        ),
        migrations.AddField(
            model_name='privateclass',
            name='teacher_hourly_in_original',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Teacher hourly rate in original currency (before conversion to QAR)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='teacher_currency',
            field=models.CharField(choices=[('QAR', 'QAR - Qatari Riyal'), ('USD', 'USD - US Dollar'), ('GBP', 'GBP - British Pound'), ('JOD', 'JOD - Jordanian Dinar'), ('EGP', 'EGP - Egyptian Pound')], default='QAR', max_length=3),
        ),
        migrations.AddField(
            model_name='project',
            name='teacher_exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, help_text='Exchange rate used: 1 teacher currency = X QAR', max_digits=10),
        ),
        migrations.AddField(
            model_name='project',
            name='teacher_fee_in_original',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Teacher fee in original currency (before conversion to QAR)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='teacher_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Teacher fee in QAR', max_digits=12, null=True),
        ),
    ]
