# Generated by Django 5.1.4 on 2026-02-22 15:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_teacher_payout_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privateclass',
            name='teacher_exchange_rate',
        ),
        migrations.RemoveField(
            model_name='privateclass',
            name='teacher_hourly_in_original',
        ),
        migrations.AddField(
            model_name='privateclass',
            name='student_currency',
            field=models.CharField(choices=[('QAR', 'QAR - Qatari Riyal'), ('USD', 'USD - US Dollar'), ('GBP', 'GBP - British Pound'), ('JOD', 'JOD - Jordanian Dinar'), ('EGP', 'EGP - Egyptian Pound')], default='QAR', max_length=3),
        ),
        migrations.AlterField(
            model_name='privateclass',
            name='student_hourly_rate',
            field=models.DecimalField(decimal_places=2, help_text='Rate charged to student per hour (in student_currency)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='privateclass',
            name='teacher_hourly_rate',
            field=models.DecimalField(decimal_places=2, help_text='Rate paid to teacher per hour (in teacher_currency)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='teacher_exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, help_text='Exchange rate: 1 teacher currency = X QAR', max_digits=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='teacher_fee_in_original',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Teacher fee in original currency', max_digits=12, null=True),
        ),
    ]
