# Generated by Django 5.1.4 on 2026-02-22 15:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_teacher_currency_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('currency', models.CharField(choices=[('QAR', 'QAR - Qatari Riyal'), ('USD', 'USD - US Dollar'), ('GBP', 'GBP - British Pound'), ('JOD', 'JOD - Jordanian Dinar'), ('EGP', 'EGP - Egyptian Pound')], default='QAR', max_length=3)),
                ('amount_qar', models.DecimalField(decimal_places=2, help_text='Amount in QAR (auto-calculated)', max_digits=12)),
                ('paid_date', models.DateField()),
                ('payment_method', models.CharField(blank=True, default='', max_length=50)),
                ('receipt_number', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classes', models.ManyToManyField(blank=True, help_text='Classes covered by this payment', related_name='class_payments', to='core.privateclass')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_payments', to='core.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_payments', to='core.student')),
            ],
            options={
                'ordering': ['-paid_date', '-created_at'],
            },
        ),
    ]
